### ISSUE TITLE
Add a way to clear the tile away

### ISSUE THREAD

**Issue by Puddinglord** [EvanesceExotica/Journal-To-Canvas-Slideshow#1]
I love being able to show images but when I'm done I want to be able to clear away the image to have a fresh start.

**Comment by EvanesceExotica** [comment]
> I love being able to show images but when I'm done I want to be able to clear away the image to have a fresh start.

Sure thing! I could add something like a button to the Tile HUD that will give the tile a completely transparent image when you click it, so that it just shows the background behind it. Would something like that work? 

![image](https://user-images.githubusercontent.com/13098820/103105696-5d57a700-45fd-11eb-8324-e3ac3d0c0012.png)

**Comment by Puddinglord** [comment]
That would be perfect. In your image on the left are the tools. If you could put that button in there below that stop hand ✋ that would be a perfect solution!

**Comment by EvanesceExotica** [comment]
Hey there! I've added a button in the Tile controls to clear the tile/make it transparent now in version 0.1.1. You can take a look at the Changelog in the ReadMe to see where it's located and how it works. Enjoy!
