### ISSUE TITLE
Some images doesnt show on scene

### ISSUE THREAD

**Issue by cefasheli** [EvanesceExotica/Journal-To-Canvas-Slideshow#18]
Some urls like these doesnt show on scene and other works. Look theses examples that don't work:

https://observatoriodocinema.uol.com.br/wp-content/uploads/2018/04/2-51-670x277.jpg
https://www.paraentender.com.br/wp-content/uploads/2014/11/corvo-625x542.jpg
https://observatoriodocinema.uol.com.br/wp-content/uploads/2021/01/httpstigsaxblogspotcom201011thors-fishing-trip_1024x1024.jpg

**Comment by EvanesceExotica** [comment]
Hey, there!

Unfortunately, I think this isn't so much an issue with my module as it is with the website you're getting the URL from and how that interacts with Foundry. 

(After trying to get the images to display, you can press F12 to open the developer's console, and see if you have an error highlighted in red that looks like this https://i.imgur.com/SBHQPka.png. I tested out those URLs you shared and that is what showed for me. )

As I understand it, some URLs simply won't work in Foundry because of something called Cross-Origin Resource Sharing. I'm not sure if there's an easy solution that I could implement. 

So for now the best solution might be to download the image locally and use the file path, or upload it to an image-hosting site like [Imgur ](https://imgur.com/)and link it from there. 

I know it's inconvenient and wish there was a better solution. :( Apologies. 

Here's some more information.
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by cefasheli** [comment]
Thanks you anyway! This is a great module and i'm in love with it!
