### ISSUE TITLE
Sugestion about interface

### ISSUE THREAD

**Issue by jacksands** [EvanesceExotica/Journal-To-Canvas-Slideshow#32]
Hi! and tks for one of my favorite modules!  I even made a tutorial about how to use it and token magic fx to make a monitor like effect and similar! !

I have a small suggestion, another module, "share media" seems to be inspired by yours but can't make use of fx for example... like yours more!  But it has an easier interface for choosing where to show the image.. can you make something similar?

I really like your module and I will keep using! is just a suggestion!

Tks for you work!

Erich
![Screenshot_2](https://user-images.githubusercontent.com/7229143/172843044-de0b16f7-6eee-4d3c-b126-50880149c577.png)

**Comment by EvanesceExotica** [comment]
Ah, thank you! I'm so glad you're enjoying it! I'm not the most experienced
dev haha, but I've learned a whole lot since I last worked on this module,
so I can certainly give your suggestion a try!

**Comment by jacksands** [comment]
I can only be thankful for your effort!  =D

**Comment by EvanesceExotica** [comment]
Hello! Thank you so much for your patience over the past few months.

Your kind words really inspired me, and after a lot of hard work, I took your suggestion added a lot of new and improved controls and functionality to this module, hopefully making it a whole lot easier and more fun to use. 

These updates should be officially published in v2.1! 

Here's a peek at some of the updated controls:

![New Controls Preview](https://media.giphy.com/media/2b9cnHKeNs9ti18lDc/giphy.gif) 

![New Controls Preview 2](https://media.giphy.com/media/NV4MlgSyumCHc7RhWz/giphy.gif)


And a document that walks through all of the new functionality: [Features and Walkthrough](https://github.com/EvanesceExotica/Journal-To-Canvas-Slideshow/blob/master/features-and-walkthrough.md)

I hope you enjoy! 

Note:  The name of the module has changed from "Journal to Canvas Slideshow" to "JTCS - Art Gallery" in case you're having a hard time finding it. 

Also, the officially published version (v.2.1) only supports Foundry v9, so if you've updated your Foundry to Foundry v10 since then, I've been working on a pre-release version of this module that does support v10 (and should be backwards compatible with v9 as well).

I have tested the pre-release version in Foundry v10 and v9 and most of the basic functionality seems to work, but it could use further testing before I publish it officially.

To try the experimental v10 version, just paste the link below into the text box at the bottom of the "Install Module" window and press "Install" to install it:



https://raw.githubusercontent.com/EvanesceExotica/Journal-To-Canvas-Slideshow/v10-migration-experimental/module.json

![manifest url install](https://user-images.githubusercontent.com/13098820/194378787-4b03dc58-7361-4392-ae5b-c9edb0b8b663.png)


Let me know if you have any issues or further suggestions!/requests!

**Comment by jacksands** [comment]
FANTASTIC WORK!!!!!

Really amazing! I'll test it as soon as possible!!!

**Comment by jacksands** [comment]
Wow!!!  just Wow!!!

This is just amazing!

As a quick test I used Token Magic FX and it also still works flawlessly!

![image](https://user-images.githubusercontent.com/7229143/194543818-0d37989f-e01c-4876-8376-4828d77b06f2.png)

I cant imagine the level of Codemancy Magic that you used to do this! 

Really amazing and I cannot thank you enough for your effort...

but just as a note, I cant make it show the controls on monk enhanced journal, and to activate on it I need first to disable the Monk module, activate your settings on that journal and than reactivate the Monks... 

![image](https://user-images.githubusercontent.com/7229143/194544626-dac8ed8a-23f2-41ad-b53a-55bb5a46e33a.png)

But I still using your module regardless of monks!

And you said you are not a experienced dev!!!  Imagine otherwise... you would be working for Hideo Kojima! kkkk

Once again! tks!

**Comment by EvanesceExotica** [comment]
You're welcome, and thank you so much too! You're so kind, and I'm so happy you're enjoying my module! <3 I'll definitely take a look into adding some support for Monk's Journal too at some point so you can use both!

Best wishes and have fun!

**Comment by jacksands** [comment]
I'm not kind, you made an amazing work and deserves de compliment!
Also it's good when we make contact with someone and receives a positive return! speaking with you has been awesome!

It would be nice to keep contact! 

Now, just a question... your module supports video? can't find a way to make it function

Erich

**Comment by EvanesceExotica** [comment]
Thank you so much! It's been really nice to speak with you as well! ^ ^ 

And yes, it should support video! I realized it's something I forgot to put on the tutorial page haha. 

So in order to put a video in a journal entry, you should be able to use HTML "video" tags. Here are a few links with information on how they work. 

https://www.w3schools.com/tags/tag_video.asp
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

Basically you'd take something like the code below and place it in your journal entry source code.

```
<video width="320" height="240" controls>
  <source src="movie.mp4" type="video/mp4">
</video> 
```
or
```
<video src="video.mp4"></video>
```

![Source Code Demo](https://user-images.githubusercontent.com/13098820/195217359-7ac8d2cd-c16b-4e62-85f3-87242b769899.png)

You'd want to place your video url or path in-between the quotations of the `src="..."` part. 

![FoundryVTT Video Tag demo](https://user-images.githubusercontent.com/13098820/195211563-48716b58-939f-4946-bfd1-40e8a0c967da.png)

Here's a quick example with some gifs: 

![Demo gif 0](https://media.giphy.com/media/9xZqKKbD5wulLKvpsK/giphy.gif)
![Demo gif 1](https://media.giphy.com/media/zAjx0WkDIhYNMJ7zEI/giphy.gif)
![Demo gif 2](https://media.giphy.com/media/7mowUZRZR1ROPF0NgP/giphy.gif)

Hope that helps!

**Comment by jacksands** [comment]
Thank you! You even take the time to make this amazing manual, with animations! 
I knew about the video HTML tags, but never used without "controls".
Here only without controls the module icons appears...

perhaps I'm doing something wrong...

but at least I can use now!  thanks!

https://user-images.githubusercontent.com/7229143/195552391-b4e763e8-ea98-425f-bbbf-8a88e3f8d3d7.mp4



And it seems that you enjoy oriental theme RPG! Nice images!

**Comment by Evannessa** [comment]
No problem, and thank you! ^ ^ I'll take a look at the video with and without controls issue for you!
