### ISSUE TITLE
Fail to use video

### ISSUE THREAD

**Issue by brunocalado** [EvanesceExotica/Journal-To-Canvas-Slideshow#5]
Hi.

I'm having trouble to use video. Can you help me?

Both of the codes don't show the video and result in a error.

```
<p><video controls="controls" width="320" height="240">
<source src="worlds/testesdndlimpo/video2.mp4" type="video/mp4" />
</video></p>
```

```
<p><video controls="controls" width="320" height="240">
<source src="worlds/testesdndlimpo/video.webm" type="video/webm" />
</video></p>
```

![image](https://user-images.githubusercontent.com/4999783/106386727-2e2f1500-63b5-11eb-82d1-8ae0e1fb3b1d.png)

**Comment by EvanesceExotica** [comment]
Sure, I can try and help! I'm not sure if this particular issue has to do
with my module itself, but I'll try my best to help out.

First, could you open up the developer's console and take a screenshot of
what's there? It should be F12 to open, and any errors will be highlighted
in red.

**Comment by brunocalado** [comment]
The problem is I can't send a video to a Journal like a can send it to the Scene.

**Comment by EvanesceExotica** [comment]
Got it! Sorry, I responded late last night when I was tired and didn't fully understand. 

I think I realize what the issue is. I don't currently think it's possible to use a video in an Image Mode journal entry like you can on a tile in a scene. I've been a little swamped with schoolwork lately so that's a limitation I forgot to mention in the ReadMe. 

However, I do intend to change the way this works in the next update, and a user named DarKDinDoN has made a pull request where they implemented this feature in a different way, and I intend to merge it once I make some changes on my end.

Sorry for the inconvenience!

**Comment by brunocalado** [comment]
Thank you.
